[package]
edition = "2024"
name = "ui"
version = "0.1.0"

[dependencies]
defmt = "1.0.1"
embedded-graphics = "0.8.2"
no_std_strings = "0.1.3"
profont = "0.7.0"
embedded-text = "0.7.3"
embedded-graphics-framebuf = "0.5.0"
ryu = "1.0.23"
static_cell = "2.1.1"
